#! /bin/bash

pgrep -x sxhkd >/dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
~/.config/polybar/launch.sh &
pgrep -x dunst >/dev/null || dunst -config $HOME/.config/bspwm/dunstrc &
pgrep -x picom >/dev/null || picom --config $HOME/.config/bspwm/picom.conf &
#nitrogen --restore
wal -R &
/usr/libexec/polkit-gnome-authentication-agent-1 &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config presel_feedback_color "#d4be98"

# Scratch pads
bspc rule -a mysp state=floating rectangle=1280x800+380+170
bspc rule -a scp2 state=floating rectangle=1280x800+380+170
bspc rule -a pulse state=floating rectangle=1280x800+380+170
bspc rule -a music state=floating rectangle=1280x800+380+170
bspc rule -a news state=floating rectangle=1280x800+380+170
bspc rule -a ranger state=floating rectangle=1280x800+380+170
# Theme concept from https://github.com/Sinomor/dots/tree/main

bspc rule -a feh state=fullscreen

# Restore wallpaper
feh --bg-fill ~/Pictures/Wallpapers/debian-black-4k.png
